package View;

import datechooser.beans.DateChooserCombo;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author lucia
 */
public class ViewCarrera extends javax.swing.JFrame {

    public ViewCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAlumno = new javax.swing.JPanel();
        jLAlumnoTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrera = new javax.swing.JTable();
        jLCodCarrera = new javax.swing.JLabel();
        jTCodCarrera = new javax.swing.JTextField();
        jLNombreCarrrera = new javax.swing.JLabel();
        jTNombreCarrera = new javax.swing.JTextField();
        jLDuracion = new javax.swing.JLabel();
        jTDuracion = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAlumno.setBackground(new java.awt.Color(127, 175, 207));

        jLAlumnoTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLAlumnoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLAlumnoTitulo.setText("CARRERA");

        jTableCarrera.setBackground(new java.awt.Color(255, 253, 232));
        jTableCarrera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableCarrera.setForeground(new java.awt.Color(51, 51, 51));
        jTableCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableCarrera.setGridColor(new java.awt.Color(0, 0, 0));
        jTableCarrera.setRowHeight(20);
        jScrollPane1.setViewportView(jTableCarrera);

        jLCodCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCodCarrera.setForeground(new java.awt.Color(51, 51, 51));
        jLCodCarrera.setText("COD. CARRERA");

        jTCodCarrera.setBackground(new java.awt.Color(255, 253, 232));
        jTCodCarrera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLNombreCarrrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNombreCarrrera.setForeground(new java.awt.Color(51, 51, 51));
        jLNombreCarrrera.setText("CARRERA");

        jTNombreCarrera.setBackground(new java.awt.Color(255, 253, 232));
        jTNombreCarrera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLDuracion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDuracion.setForeground(new java.awt.Color(51, 51, 51));
        jLDuracion.setText("DURACIÓN");

        jTDuracion.setBackground(new java.awt.Color(255, 253, 232));
        jTDuracion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jBGuardar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/boton agregar.png"))); // NOI18N
        jBGuardar.setText("NUEVO");
        jBGuardar.setMaximumSize(new java.awt.Dimension(140, 57));
        jBGuardar.setMinimumSize(new java.awt.Dimension(140, 57));

        jBVolver.setBackground(new java.awt.Color(204, 204, 204));
        jBVolver.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(51, 51, 51));
        jBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/volver.png"))); // NOI18N
        jBVolver.setText("ATRAS");

        jBEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jBEliminar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/eliminar.png"))); // NOI18N
        jBEliminar.setText("BORRAR");

        jBModificar.setBackground(new java.awt.Color(204, 204, 204));
        jBModificar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(51, 51, 51));
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/editar.png"))); // NOI18N
        jBModificar.setText("EDITAR");
        jBModificar.setMaximumSize(new java.awt.Dimension(140, 57));
        jBModificar.setMinimumSize(new java.awt.Dimension(140, 57));

        javax.swing.GroupLayout jPAlumnoLayout = new javax.swing.GroupLayout(jPAlumno);
        jPAlumno.setLayout(jPAlumnoLayout);
        jPAlumnoLayout.setHorizontalGroup(
            jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlumnoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlumnoLayout.createSequentialGroup()
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLCodCarrera)
                            .addComponent(jLNombreCarrrera)
                            .addComponent(jLDuracion))
                        .addGap(18, 18, 18)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombreCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPAlumnoLayout.createSequentialGroup()
                                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBVolver))))
                    .addComponent(jLAlumnoTitulo))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPAlumnoLayout.setVerticalGroup(
            jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlumnoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLAlumnoTitulo)
                .addGap(48, 48, 48)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlumnoLayout.createSequentialGroup()
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodCarrera)
                            .addComponent(jTCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombreCarrrera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDuracion)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getjTCodCarrera() {
        return jTCodCarrera;
    }

    public void setjTCodCarrera(JTextField jTCodCarrera) {
        this.jTCodCarrera = jTCodCarrera;
    }

    public JTextField getjTDuracion() {
        return jTDuracion;
    }

    public void setjTDuracion(JTextField jTDuracion) {
        this.jTDuracion = jTDuracion;
    }

    public JTextField getjTNombreCarrera() {
        return jTNombreCarrera;
    }

    public void setjTNombreCarrera(JTextField jTNombreCarrera) {
        this.jTNombreCarrera = jTNombreCarrera;
    }

    public JTable getjTableCarrera() {
        return jTableCarrera;
    }

    public void setjTableCarrera(JTable jTableCarrera) {
        this.jTableCarrera = jTableCarrera;
    }

    public JButton getjBGuardar() {
        return jBGuardar;
    }

    public void setjBGuardar(JButton jBGuardar) {
        this.jBGuardar = jBGuardar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JButton getjBVolver() {
        return jBVolver;
    }

    public JButton getjBEliminar() {
        return jBEliminar;
    }

    public JButton getjBModificar() {
        return jBModificar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAlumno().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLAlumnoTitulo;
    private javax.swing.JLabel jLCodCarrera;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLNombreCarrrera;
    private javax.swing.JPanel jPAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodCarrera;
    private javax.swing.JTextField jTDuracion;
    private javax.swing.JTextField jTNombreCarrera;
    private javax.swing.JTable jTableCarrera;
    // End of variables declaration//GEN-END:variables
}
