package View;

import datechooser.beans.DateChooserCombo;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author lucia
 */
public class ViewProfesor extends javax.swing.JFrame {

    public ViewProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAlumno = new javax.swing.JPanel();
        jLAlumnoTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesor = new javax.swing.JTable();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLDNI = new javax.swing.JLabel();
        jTDNI = new javax.swing.JTextField();
        jLDomicilio = new javax.swing.JLabel();
        jTDomicilio = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        dateChooser = new datechooser.beans.DateChooserCombo();
        jLFechaNac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAlumno.setBackground(new java.awt.Color(127, 175, 207));

        jLAlumnoTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLAlumnoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLAlumnoTitulo.setText("PROFESOR");

        jTableProfesor.setBackground(new java.awt.Color(255, 253, 232));
        jTableProfesor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableProfesor.setForeground(new java.awt.Color(51, 51, 51));
        jTableProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProfesor.setGridColor(new java.awt.Color(0, 0, 0));
        jTableProfesor.setRowHeight(20);
        jScrollPane1.setViewportView(jTableProfesor);

        jLNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLNombre.setText("NOMBRE");

        jTNombre.setBackground(new java.awt.Color(255, 253, 232));
        jTNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLApellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(51, 51, 51));
        jLApellido.setText("APELLIDO");

        jTApellido.setBackground(new java.awt.Color(255, 253, 232));
        jTApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLDNI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDNI.setForeground(new java.awt.Color(51, 51, 51));
        jLDNI.setText("DNI");

        jTDNI.setBackground(new java.awt.Color(255, 253, 232));
        jTDNI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLDomicilio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDomicilio.setForeground(new java.awt.Color(51, 51, 51));
        jLDomicilio.setText("DOMICILIO");

        jTDomicilio.setBackground(new java.awt.Color(255, 253, 232));
        jTDomicilio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jLTelefono.setText("TELÉFONO");

        jTTelefono.setBackground(new java.awt.Color(255, 253, 232));
        jTTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jBGuardar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/boton agregar.png"))); // NOI18N
        jBGuardar.setText("NUEVO");

        jBVolver.setBackground(new java.awt.Color(204, 204, 204));
        jBVolver.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(51, 51, 51));
        jBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/volver.png"))); // NOI18N
        jBVolver.setText("ATRAS");

        jBEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jBEliminar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/eliminar.png"))); // NOI18N
        jBEliminar.setText("BORRAR");

        jBModificar.setBackground(new java.awt.Color(204, 204, 204));
        jBModificar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(51, 51, 51));
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/editar.png"))); // NOI18N
        jBModificar.setText("EDITAR");

        dateChooser.setFormat(2);
        dateChooser.setFieldFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        dateChooser.setLocale(new java.util.Locale("lt", "", ""));

        jLFechaNac.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLFechaNac.setForeground(new java.awt.Color(51, 51, 51));
        jLFechaNac.setText("FECHA NAC");

        javax.swing.GroupLayout jPAlumnoLayout = new javax.swing.GroupLayout(jPAlumno);
        jPAlumno.setLayout(jPAlumnoLayout);
        jPAlumnoLayout.setHorizontalGroup(
            jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlumnoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlumnoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAlumnoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLApellido)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLDNI)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLDomicilio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLFechaNac)
                                    .addGap(18, 18, 18)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAlumnoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPAlumnoLayout.createSequentialGroup()
                                .addComponent(jBGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jBModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jBEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBVolver))))
                    .addComponent(jLAlumnoTitulo))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPAlumnoLayout.setVerticalGroup(
            jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlumnoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLAlumnoTitulo)
                .addGap(81, 81, 81)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlumnoLayout.createSequentialGroup()
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLApellido))
                        .addGap(18, 18, 18)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFechaNac))
                        .addGap(18, 18, 18)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAlumnoLayout.createSequentialGroup()
                                .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDomicilio)))
                            .addComponent(jLDNI))
                        .addGap(18, 18, 18)
                        .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTelefono)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBVolver)
                    .addGroup(jPAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBGuardar)
                        .addComponent(jBModificar)
                        .addComponent(jBEliminar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DateChooserCombo getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(DateChooserCombo dateChooser) {
        this.dateChooser = dateChooser;
    }

    public JButton getjBGuardar() {
        return jBGuardar;
    }

    public void setjBGuardar(JButton jBGuardar) {
        this.jBGuardar = jBGuardar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getjTApellido() {
        return jTApellido;
    }

    public void setjTApellido(JTextField jTApellido) {
        this.jTApellido = jTApellido;
    }

    public JTextField getjTDNI() {
        return jTDNI;
    }

    public void setjTDNI(JTextField jTDNI) {
        this.jTDNI = jTDNI;
    }

    public JTextField getjTDomicilio() {
        return jTDomicilio;
    }

    public void setjTDomicilio(JTextField jTDomicilio) {
        this.jTDomicilio = jTDomicilio;
    }

    public JTextField getjTNombre() {
        return jTNombre;
    }

    public void setjTNombre(JTextField jTNombre) {
        this.jTNombre = jTNombre;
    }

    public JTextField getjTTelefono() {
        return jTTelefono;
    }

    public void setjTTelefono(JTextField jTTelefono) {
        this.jTTelefono = jTTelefono;
    }

    public JTable getjTableProfesor() {
        return jTableProfesor;
    }

 
    public JButton getjBVolver() {
        return jBVolver;
    }

    public JButton getjBEliminar() {
        return jBEliminar;
    }

    public JButton getjBModificar() {
        return jBModificar;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTableProfesor(JTable jTableAlumno) {
        this.jTableProfesor = jTableAlumno;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAlumno().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLAlumnoTitulo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JPanel jPAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTable jTableProfesor;
    // End of variables declaration//GEN-END:variables
}
